version: 0.0
os: linux
files:
  - source: index.html
    destination: /tmp/index.html
hooks:
  AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
    - location: scripts/deploy_nginx.sh
      timeout: 300
      runas: root
