version: 0.2

phases:
  install:
      - echo "Creating Build"
  build:
    commands:
      - echo "Building the project..."
      - mkdir -p output
      - cp index.html output/
      - cp appspec.yml output/
      - cp scripts/setup_nginx.sh output/
artifacts:
  files:
    - output/*
